Create book crud operation
wolox-training/vda-java pull request #5
Opened 2022-06-22 13:13 UTC by vicayala82

## Summary
-created crud methods in controller class
    -new customer exception classes
    -methods get and setter for Book.id
    -New search, book for title
## Trello Card
https://trello.com/c/jez5TteF/18-crear-las-operaciones-crud-de-book

2022-06-26 05:02 UTC, juandbc requested changes

2022-06-26 05:02 UTC, juandbc commented on training/src/main/java/wolox/training/models/Book.java
> +    }
Only the ORM should control the id field. Thus, you avoid the mutation and incorrectness data
```suggestion
```

2022-06-26 05:02 UTC, juandbc commented on training/src/main/java/wolox/training/controllers/BookController.java
> +    public void delete(@PathVariable Long id) {
Here it should return a 204 status code 
```suggestion
    @DeleteMapping("/{id}")
    @ResponseStatus(HttpStatus.NO_CONTENT)
    public void delete(@PathVariable Long id) {
```

2022-06-26 05:02 UTC, juandbc commented on training/src/main/java/wolox/training/controllers/BookController.java
> +    public List findByTitle(@PathVariable String bookTitle) {
The parameterized type for the List is missing

2022-06-26 05:02 UTC, juandbc commented on training/src/main/java/wolox/training/controllers/BookController.java
> +    @GetMapping("/title/{bookTitle}")
For best practice. this should be a query param instead of path variable

2022-06-26 05:02 UTC, juandbc commented on training/src/main/java/wolox/training/exceptions/BookIdMismatchException.java
> +@ResponseStatus(code = HttpStatus.BAD_REQUEST, reason = "Actor Not Found")
This reason does not correspond
```suggestion
@ResponseStatus(code = HttpStatus.BAD_REQUEST, reason = "Id mismatch")
```

2022-06-26 05:02 UTC, juandbc commented on training/src/main/java/wolox/training/exceptions/RestExceptionHandler.java
> +}
When you use the `@ResponseStatus` annotation, you don't need to use the exception handler. The default Spring Exception Resolver use the code, reason and the exception message to build the response
```suggestion
```

2022-06-26 05:02 UTC, juandbc commented on training/src/main/java/wolox/training/exceptions/BookNotFoundException.java
> +        super(cause);
You can declare the message in the constructor
```suggestion
        super( "Book not found");
    }
```

2022-06-26 05:02 UTC, juandbc commented on training/src/main/java/wolox/training/exceptions/BookIdMismatchException.java
> +        super(cause);
You can declare the message in the constructor
```suggestion
        super("The book's id does not correspond to the data to be updated");
```

2022-06-28 13:29 UTC, vicayala82 commented on training/src/main/java/wolox/training/controllers/BookController.java
> +    public List findByTitle(@PathVariable String bookTitle) {
Yes these was add in others commits, thanks

2022-06-28 14:21 UTC, vicayala82 commented on training/src/main/java/wolox/training/controllers/BookController.java
> +    @GetMapping("/title/{bookTitle}")
I will change this method thanks

2022-06-29 14:29 UTC, juandbc requested changes

2022-06-29 14:29 UTC, juandbc commented on training/src/main/java/wolox/training/controllers/BookController.java
> +    @GetMapping("/title")
Here title is treated as path variable
```suggestion
    @GetMapping
```

2022-06-29 14:39 UTC, juandbc requested changes

2022-06-29 14:39 UTC, juandbc commented on training/src/main/java/wolox/training/controllers/BookController.java
> +    public List<Book> findByTitle(@RequestParam() String bookTitle) {
If you don't specify a name in the `@RequestParam` annotation, Spring use the param's name for resolve the query param at the URL. It's better to use the same name of the entity
```suggestion
    public List<Book> findByTitle(@RequestParam String title) {
```

2022-06-30 17:50 UTC, juandbc approved these changes

2022-06-30 17:50 UTC, merged