Create user model class
wolox-training/vda-java pull request #7
Opened 2022-06-22 21:49 UTC by vicayala82

## Summary
-Created User model class
    -Created methods for add and remove book of collection
    -Created model relationship user whit book
    -Created BookAlreadyOwnedException class
## Trello Card
https://trello.com/c/2fqH75mu/19-crear-modelo-de-user

2022-06-27 01:31 UTC, juandbc requested changes

2022-06-27 01:31 UTC, juandbc commented on training/src/main/java/wolox/training/models/User.java
> +    @GeneratedValue(strategy = GenerationType.AUTO)
```suggestion
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
```

2022-06-27 01:31 UTC, juandbc commented on training/src/main/java/wolox/training/exceptions/BookAlreadyOwnedException.java
> +@ResponseStatus(code = HttpStatus.BAD_REQUEST, reason = "Actor Not Found")
This should return a conflict a status

2022-06-27 01:31 UTC, juandbc commented on training/src/main/java/wolox/training/exceptions/BookAlreadyOwnedException.java
> +        super(message);
Like the other exceptions, you can leave the message here

2022-06-27 01:31 UTC, juandbc commented on training/src/main/java/wolox/training/models/User.java
> +    }
```suggestion
```

2022-06-27 01:31 UTC, juandbc commented on training/src/main/java/wolox/training/models/User.java
> +    @OneToMany(mappedBy = "user", cascade = CascadeType.ALL)
In the most scenarios, it is better to use the merge cascade. Thus, you avoid to delete data and relationships
```suggestion
    @OneToMany(mappedBy = "user", cascade = CascadeType.MERGE)
```

2022-06-28 15:27 UTC, vicayala82 commented on training/src/main/java/wolox/training/exceptions/BookAlreadyOwnedException.java
> +        super(message);
I fixed it new commit

2022-06-29 14:41 UTC, juandbc approved these changes

2022-06-30 17:56 UTC, merged