Create user contoller
wolox-training/vda-java pull request #9
Opened 2022-06-23 15:43 UTC by vicayala82

## Summary
-Created UserCrontroller class
-Created Exceptions UserIdMismatchException and UserNotFoundException
-Created CRUD methods for user controller
-Update some book logic
card
https://trello.com/c/SeUuyKTK/21-crear-user-controller-con-las-operaciones-crud-de-user

2022-06-27 04:23 UTC, juandbc requested changes

2022-06-27 04:23 UTC, juandbc commented on training/src/main/java/wolox/training/exceptions/UserIdMismatchException.java
> +@ResponseStatus(code = HttpStatus.BAD_REQUEST, reason = "User Not Found")
Here the reason does not match

2022-06-27 04:23 UTC, juandbc commented on training/src/main/java/wolox/training/controllers/UserController.java
> +    @PatchMapping(path = "/{userID}/books/add")
The placeholder should match to the method's param. On the other hand, when working with REST, the convention says that we should use the HTTP verbs to indicate CRUD actions instead of an URL path.
In this case, is better to use POST.  PATCH and PUT are for update resources and you are creating a relation between book and user
```suggestion
    @PostMapping(path = "/{userId}/books")
```

2022-06-27 04:23 UTC, juandbc commented on training/src/main/java/wolox/training/controllers/UserController.java
> +    @PatchMapping(path = "/{userID}/books/delete")
Like the previous comment
```suggestion
    @DeleteMapping(path = "/{userId}/books")
```

2022-06-28 16:15 UTC, vicayala82 commented on training/src/main/java/wolox/training/exceptions/UserIdMismatchException.java
> +@ResponseStatus(code = HttpStatus.BAD_REQUEST, reason = "User Not Found")
Fixed

2022-06-28 16:16 UTC, vicayala82 commented on training/src/main/java/wolox/training/controllers/UserController.java
> +    @PatchMapping(path = "/{userID}/books/delete")
Understood, thanks

2022-06-30 17:59 UTC, juandbc approved these changes

2022-06-30 17:59 UTC, merged